[package]
name = "getbib"
version = "0.1.0"
edition = "2021"
authors = ["Nathan Constantine-Cooke <nathan.constantine-cooke@ed.ac.uk>"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.1", features = ["full"] }
futures = "0.3"
doi2bib = "0.1.5"
clap = {version = "4.1.4", features = ["derive"] }
