[package]
name = "bibget"
version = "1.0.0"
edition = "2021"
authors = ["Nathan Constantine-Cooke <nathan.constantine-cooke@ed.ac.uk>"]
license = "MIT OR Apache-2.0"
keywords = ["BibTeX"]
categories = ["command-line-utilities"]
description = "CLI tool to generate a BibTex entry from a DOI"
readme = "README.md"
homepage = "https://github.com/nathansam/bibget"
repository = "https://github.com/nathansam/bibget"

[dependencies]
tokio = { version = "1.26.0", features = ["full"], default-features = false }
futures = { default-features = false, version = "0.3.26" }
doi2bib = "0.1.5"
clap = {version = "4.1.13", features = ["derive", "std"], default-features = false }

[dev-dependencies]
assert_cmd = "2.0.10"
predicates = "2.1.5"
assert_fs = "1.0.10"

[profile.release]
strip = true
lto = true
codegen-units = 1
