name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '0 6 1,14,28 * *'

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cargo fmt -- --check
        uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all --check

  test:
    name: Test
    needs: [style]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build: [stable, nightly]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build debug
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.build }}
      - run: cargo build
      - run: cargo test --all --verbose
      
  Coverage:
    name: Coverage
    needs: [test]
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}} 
          fail_ci_if_error: true
      - name: Upload artefact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Coverage
          path: cobertura.xml
