name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  schedule:
    - cron: '0 6 1,14,28 * *'

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cargo fmt -- --check
        uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all --check

  test:
    name: Test
    needs: [style]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build: [stable, nightly]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build debug
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.build }}
      - run: cargo build
      - run: cargo test --all --verbose
      
  Coverage:
    name: Upload Test Coverage
    needs: [style, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-tarpaulin
      - run: cargo tarpaulin 
      
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml
